# -*- coding: utf-8 -*-
"""🧪 Lab - Ladder Part 1 - Numbers, Variables, and Math

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OcKA0yAGK6Z9XZyXOIvFYZN9WjjKlUoC

<div>
<img src="https://coursereport-s3-production.global.ssl.fastly.net/uploads/school/logo/219/original/CT_LOGO_NEW.jpg" width=60>
</div>

# **Python Ladder Challenges - Numbers, Variables, and Math**

# Climb the Ladder!
Our class moves quickly! Sometimes, it feels like we make leaps in logic that are a bit too big. Learn Python _slowly_, by doing many, many examples. Problems in this notebook start out easy and progressively get harder, so that the next rung of the Python ladder is always within reach.

# Section I: Numbers, variables, and math.

1) What is 13579 times 86420? - I'll help you get started!
"""

13579 * 86420

"""2) What is 10000 divided by 4?"""



"""3) What is 123456789 + 987654321?"""



"""4) What is 50 - 130?"""



"""5) Create a variable `num` and assign a number to it. Print the square and cube of that number.


"""



"""6) You're shopping, and one of your favorite products, usually priced at $50, is currently on sale with a 25% discount! Utilize the provided variables to compute the updated price of your beloved product. ***Keep in mind, we're interested in determining the new price of the product, not the amount of the discount.***"""

regular_price = 50
discount = 0.25

"""7) The temperature is currently 30$^{\circ}$C! Calculate its equivalent in Fahrenheit using the formula $F = \frac{9}{5}C+32$"""



"""8) Set up two variables, `height` and `base`, to represent the dimensions of a triangle. Assign the value 5 to the variable `height` and the value 12 to the variable `base`."""



"""9) Utilize the previously defined variables, `height` and `base`, to determine the area of the triangle. Recall that the formula for the area of a triangle is $A = \frac{1}{2}bh$."""



"""10) The speed of light $c$ is 300,000,000 m/s. The binding energy of a given particle is $E = mc^2$. Compute $E$ for a given particle that has mass of 17kg."""



"""11) You have $500 in an account that compounds 6% interest annually. How much money will you have after 5 years? The formula for this calculation is:

$$\text{Final amount} = A(1 + r)^t$$

Where $A$ is the initial amount, $r$ is the interest rate, and $t$ is the number of years.
"""

